//
// Created by niels on 4/10/21.
//

#ifndef INC_2DSIDESCROLLER_DEFS_H
#define INC_2DSIDESCROLLER_DEFS_H

#define TITLE "2D SideScroller"
#define SCREEN_WIDTH 64*20
#define SCREEN_HEIGHT 64*13
#define LEVEL_HEIGHT 64*25
#define LEVEL_WIDTH 200 * 64
#define BACKGROUND_WIDTH 1456

#endif //INC_2DSIDESCROLLER_DEFS_H
