//
// Created by niels on 4/12/21.
//

#ifndef INC_2DSIDESCROLLER_PHYSICSMANAGER_H
#define INC_2DSIDESCROLLER_PHYSICSMANAGER_H

#define GRAVITY 1.0
#define MAX_FALLING_SPEED 17
#define PLAYER_SPEED 4
#define CROUCH_SPEED 2
#define JUMP_SPEED 25
#define DOUBLE_JUMP_SPEED 17.8
#define SAW_FLYAWAY_X_FACTOR 40
#define SAW_FLYAWAY_Y_FACTOR 25
#define SAW_FLYAWAY_SLOWDOWN_X_PRODUCT 0.97
#define HURT_DURATION 120
#define SKELETON_SPEED 2
#define SKELETON_HURT_SLOW_DOWN_X_PRODUCT 0.97
#define SKELETON_TIME_BETWEEN_ATTACKS 300
#define SKELETON_ATTACK_MIN_PLAYER_DISTANCE 100

#endif //INC_2DSIDESCROLLER_PHYSICSMANAGER_H
