//
// Created by niels on 4/12/21.
//

#ifndef INC_2DSIDESCROLLER_PHYSICSMANAGER_H
#define INC_2DSIDESCROLLER_PHYSICSMANAGER_H

#define GRAVITY 1.0
#define MAX_FALLING_SPEED 17
#define PLAYER_SPEED 4
#define CROUCH_SPEED 2
#define JUMP_SPEED 25
#define DOUBLE_JUMP_SPEED 17.8
#define OUTWARD_FORCE_SAW_X 5
#define OUTWARD_FORCE_SAW_Y 10
#define MIN_OUTWARD_FORCE_SAW 1
#define EXTRA_SAW_X_FORCE_IF_UNDER_MIN 12
#define EXTRA_SAW_Y_FORCE_IF_UNDER_MIN 18
#define SAW_FLYAWAY_SLOWDOWN_X_PRODUCT 0.97
#define HURT_DURATION 120
#define SKELETON_SPEED 2
#define SKELETON_HURT_SLOW_DOWN_X_PRODUCT 0.95
#define SKELETON_TIME_BETWEEN_ATTACKS 300
#define SKELETON_ATTACK_MIN_PLAYER_DISTANCE 100
#define SKELETON_ATTACK_DURATION 30
#define PLAYER_SKELETON_HIT_PUSH 4
#define MAGE_SPEED 2
#define MAGE_ATTACK_RANGE 600
#define MAGE_BULLET_SPEED 4
#define MAGE_SECONDS_BETWEEN_ATTACK 2
#define PLAYER_BULLET_MIN_POOLSIZE 3
#define SECONDS_DEAD_BEFORE_REWINDING 3
#define PLAYER_DEAD_REWIND_SPEED 3.5
#define MIN_TIME_BETWEEN_PLAYER_BULLETS 10
#define SKELETON_ATTACK_DAMAGE 20
#define MAGE_ATTACK_DAMAGE 25
#define SAW_ATTACK_DAMAGE 40
#define SPIKE_ATTACK_DAMAGE 100

#endif //INC_2DSIDESCROLLER_PHYSICSMANAGER_H
